services:
  postgres_pipeline:
    image: postgres:16-alpine
    ports:
      - "${PIPELINE_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_pipeline_data:/var/lib/postgresql/data
      - ./schema:/schema
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres_airflow:
    image: postgres:16-alpine
    ports:
      - "${AIRFLOW_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_AIRFLOW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AIRFLOW_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AIRFLOW_DB}
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_AIRFLOW_USER} -d ${POSTGRES_AIRFLOW_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres_pipeline

  airflow-init:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@postgres_airflow:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_HOME: /opt/airflow
      PYTHONPATH: /opt/airflow/project
      DB_HOST: postgres_pipeline
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CSV_PATH: data/data_jobs.csv
      LOG_LEVEL: ${LOG_LEVEL}
      DBT_POSTGRES_HOST: postgres_pipeline
      DBT_POSTGRES_PORT: 5432
      DBT_POSTGRES_DBNAME: ${POSTGRES_DB}
      DBT_POSTGRES_USER: ${POSTGRES_USER}
      DBT_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DBT_POSTGRES_SCHEMA: staging
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    depends_on:
      postgres_airflow:
        condition: service_healthy
    command: >
      bash -lc "airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email admin@example.com || true"

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    restart: unless-stopped
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@postgres_airflow:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_HOME: /opt/airflow
      PYTHONPATH: /opt/airflow/project
      DB_HOST: postgres_pipeline
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CSV_PATH: data/data_jobs.csv
      LOG_LEVEL: ${LOG_LEVEL}
      DBT_POSTGRES_HOST: postgres_pipeline
      DBT_POSTGRES_PORT: 5432
      DBT_POSTGRES_DBNAME: ${POSTGRES_DB}
      DBT_POSTGRES_USER: ${POSTGRES_USER}
      DBT_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DBT_POSTGRES_SCHEMA: staging
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    depends_on:
      postgres_airflow:
        condition: service_healthy
      postgres_pipeline:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: bash -lc "airflow scheduler"

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@postgres_airflow:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW_HOME: /opt/airflow
      PYTHONPATH: /opt/airflow/project
      DB_HOST: postgres_pipeline
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CSV_PATH: data/data_jobs.csv
      LOG_LEVEL: ${LOG_LEVEL}
      DBT_POSTGRES_HOST: postgres_pipeline
      DBT_POSTGRES_PORT: 5432
      DBT_POSTGRES_DBNAME: ${POSTGRES_DB}
      DBT_POSTGRES_USER: ${POSTGRES_USER}
      DBT_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DBT_POSTGRES_SCHEMA: staging
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    depends_on:
      postgres_airflow:
        condition: service_healthy
      postgres_pipeline:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: bash -lc "airflow webserver"

volumes:
  postgres_pipeline_data:
  postgres_airflow_data:
